package pl.wsb.fitnesstracker.user.api;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDate;

/**
 * Entity that represents a user in the FitnessTracker system.
 * <p>
 * The class is mapped to the {@code users} table in the database.  
 * It uses JPA/Hibernate for persistence and Lombok to generate boilerplate code.
 *
 * @author  Your Name
 * @since   1.0
 */
@Entity
@Table(name = "users")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString
public class User {

    /**
     * Primary key – auto‑generated by the database.
     * <p>
     * {@code null} when a new entity is created and not yet persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Nullable
    private Long id;

    /**
     * First name of the user.
     *
     * <p>Column: {@code first_name}, not nullable, maximum length 100 characters.</p>
     */
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    /**
     * Last name of the user.
     *
     * <p>Column: {@code last_name}, not nullable, maximum length 100 characters.</p>
     */
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /**
     * Date of birth.
     *
     * <p>Column: {@code birthdate}, not nullable.</p>
     */
    @Column(name = "birthdate", nullable = false)
    private LocalDate birthdate;

    /**
     * Email address – must be unique in the system.
     *
     * <p>Column: {@code email}, not nullable, unique, maximum length 255 characters.</p>
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /**
     * Creates a new {@code User} instance with all mandatory fields.
     *
     * @param firstName the user’s first name
     * @param lastName  the user’s last name
     * @param birthdate the user’s date of birth
     * @param email     the user’s e‑mail address (must be unique)
     */
    public User(
            final String firstName,
            final String lastName,
            final LocalDate birthdate,
            final String email) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.birthdate = birthdate;
        this.email = email;
    }

    /**
     * Updates the user’s first name.
     *
     * @param firstName new first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Updates the user’s last name.
     *
     * @param lastName new last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Updates the user’s birth date.
     *
     * @param birthdate new birth date
     */
    public void setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * Updates the user’s e‑mail address.
     *
     * @param email new e‑mail address (must remain unique)
     */
    public void setEmail(String email) {
        this.email = email;
    }
}
