spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  profiles:
    active: "loadInitialData"
    mail:
      host: "mail.example.local"
server:
  port: 8008