package pl.wsb.fitnesstracker.event;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

/**
 * Domain entity representing an event in the fitness‑tracker system.
 *
 * <p>Fields are mapped to the {@code event} table.  All fields are
 * required except for {@link #description}, which may be {@code null}.</p>
 *
 * <h3>Sample persistence</h3>
 * <pre>{@code
 * Event event = new Event("Yoga Class", "Morning yoga for beginners",
 *                         start, end, "Poland", "Warsaw");
 * eventRepository.save(event);
 * }</pre>
 *
 * @author Your Name
 * @since 1.0
 */
@Entity
@Table(name = "event")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString
public class Event {

    /** Primary key – generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the event (max 255 characters). */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Detailed description – stored as a text column. */
    @Column(name = "description", columnDefinition = "text")
    private String description;

    /** When the event starts. */
    @Column(name = "start_time", nullable = false)
    private Date startTime;

    /** When the event ends. */
    @Column(name = "end_time", nullable = false)
    private Date endTime;

    /** Country where the event takes place. */
    @Column(name = "country", nullable = false, length = 100)
    private String country;

    /** City where the event takes place. */
    @Column(name = "city", nullable = false, length = 100)
    private String city;

    /**
     * Convenience constructor for creating a fully‑populated {@link Event}.
     *
     * @param name        event name
     * @param description optional description; may be {@code null}
     * @param startTime   event start timestamp
     * @param endTime     event end timestamp
     * @param country     host country
     * @param city        host city
     */
    public Event(
            final String name,
            final String description,
            final Date startTime,
            final Date endTime,
            final String country,
            final String city) {

        this.name = name;
        this.description = description;
        this.startTime = startTime;
        this.endTime = endTime;
        this.country = country;
        this.city = city;
    }
}
