package pl.wsb.fitnesstracker.event;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import pl.wsb.fitnesstracker.user.api.User;

/**
 * Join entity that represents a user’s participation in an event.
 *
 * <p>Each {@link UserEvent} links one {@code User} to one {@code Event}
 * and stores a {@link #status} that indicates the user’s state
 * (e.g. “registered”, “attended”, “canceled”).</p>
 *
 * <h3>Typical usage</h3>
 * <pre>{@code
 * User user = userRepository.findById(userId).orElseThrow();
 * Event event = eventRepository.findById(eventId).orElseThrow();
 *
 * UserEvent participation = new UserEvent(user, event, "registered");
 * userEventRepository.save(participation);
 * }</pre>
 *
 * @author Your Name
 * @since 1.0
 */
@Entity
@Table(name = "user_event")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString
public class UserEvent {

    /** Primary key – generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Reference to the participating user. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Reference to the event the user participates in. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    /** Current status of the participation (max 50 characters). */
    @Column(name = "status", nullable = false, length = 50)
    private String status;

    /**
     * Convenience constructor for creating a new {@link UserEvent}.
     *
     * @param user   the participating user
     * @param event  the event
     * @param status current participation status
     */
    public UserEvent(
            final User user,
            final Event event,
            final String status) {

        this.user = user;
        this.event = event;
        this.status = status;
    }
}
