package pl.wsb.fitnesstracker.training.api;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import pl.wsb.fitnesstracker.training.internal.ActivityType;
import pl.wsb.fitnesstracker.user.api.User;

import java.util.Date;

/**
 * Domain entity that represents a single training session performed by a user.
 *
 * <p>Each {@code Training} contains the following information:</p>
 * <ul>
 *   <li>{@link #user} – the user who performed the training</li>
 *   <li>{@code startTime} and {@code endTime} – timestamps that define the
 *       duration of the session</li>
 *   <li>{@link #activityType} – the type of activity (e.g. RUNNING,
 *       CYCLING, SWIMMING).  The enum is stored as a string in the database.</li>
 *   <li>{@link #distance} – total distance covered (in kilometres)</li>
 *   <li>{@link #averageSpeed} – average speed during the session (in km/h)</li>
 * </ul>
 *
 * <h3>Example persistence</h3>
 * <pre>{@code
 * Training training = new Training(user, start, end,
 *                                 ActivityType.RUNNING, 10.5, 6.3);
 * trainingRepository.save(training);
 * }</pre>
 *
 * @author Your Name
 * @since 1.0
 */
@Entity
@Table(name = "trainings")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString
public class Training {

    /** Primary key – generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The user that performed the training. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** When the training started. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false)
    private Date startTime;

    /** When the training finished. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", nullable = false)
    private Date endTime;

    /** Type of activity – stored as a string in the database. */
    @Enumerated(EnumType.STRING)
    @Column(name = "activity_type", nullable = false, length = 50)
    private ActivityType activityType;

    /** Total distance covered (km). */
    @Column(name = "distance", nullable = false)
    private double distance;

    /** Average speed during the session (km/h). */
    @Column(name = "average_speed", nullable = false)
    private double averageSpeed;

    /**
     * Convenience constructor for creating a fully‑populated {@link Training}.
     *
     * @param user          the participant
     * @param startTime     training start timestamp
     * @param endTime       training end timestamp
     * @param activityType  type of the activity (must not be {@code null})
     * @param distance      total distance in kilometres
     * @param averageSpeed  mean speed in km/h
     */
    public Training(
            final User user,
            final Date startTime,
            final Date endTime,
            final ActivityType activityType,
            final double distance,
            final double averageSpeed) {

        this.user = user;
        this.startTime = startTime;
        this.endTime = endTime;
        this.activityType = activityType;
        this.distance = distance;
        this.averageSpeed = averageSpeed;
    }
}
